project:
  type: website
  resources:
    - "Resources"
    - "posts"
    - "projects"
    - "style.css"
    - "style_site.scss"
    - "style_site_dark.scss"
    - "Hal_css.css"
    - "Hal_css_dark.css"
    - "custom_hal.js"
    - "carousel.js"
  output-dir: docs


# https://icon-sets.iconify.design/ion/?icon-filter=social
website:
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: true
  open-graph: true
  title: "Thomas Lavigne"
  image: Resources/images/profile_pic2.jpeg
  favicon: Resources/images/profile_pic2.jpeg
  description: "Thomas Lavigne, PhD, biom√©canique, post doctor, personal webpage, mechanics, biomechanics, vascular, coupling, poromechanics, hydrogel, fenicsx, simulation, gmsh, porous, medium, biomechanics, CV, Bordeaux, Paris, I2M, LMS, ENS, Ecole normale sup√©rieure Paris-Saclay, ENSAM, IBHGC, website, github, links, th0maslavigne, th0mas lavigne, th0mas, lavigne, research, doctoral, post-doctoral, Universit√© du Luxembourg, Luxembourg, Legato, Team, Polytechnique"
  # keywords: "Thomas, Lavigne, Thomas Lavigne, PhD, personal webpage, biomechanics, CV, Bordeaux, Paris, I2M, LMS, ENS, Ecole normale sup√©rieure Paris-Saclay, ENSAM, IBHGC, website, github, links, th0maslavigne, th0mas lavigne, th0mas, lavigne" # Optionnel : Quarto ne g√®re pas directement une meta-tag "keywords" mais c'est bon pour la structure
  site-url: https://th0maslavigne.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: News.qmd
        text: News 
      - text: Research
        menu:
          - href: Research.qmd
            text: Projects
          - href: Publication.qmd
            text: Publications
          - href: Talks.qmd
            text: Talks
      - href: Teaching.qmd
        text: Teaching
      - href: Education.qmd
        text: Academic & Research Appointments
      - text: CV
        menu:
        - text: CV
          href: Resources/documents/CV.pdf
        - text: Narrative CV
          href: Resources/documents/Narrative_CV_Lavigne.pdf
        target: _blank
      - text: "{{< iconify ion:logo-github >}}"
        href: https://github.com/Th0masLavigne
      - text: "{{< iconify ion:flame-sharp >}}"
        href: https://th0maslavigne.github.io/FEniCSx_GMSH_tutorials/README.html
  page-footer: 
    right: |
      <ul style="list-style-type: none; padding: 0; margin: 0;">
        <li>üìç Institut Polytechnique de Paris</li>
        <li>üìß <a href="mailto:thomas.lavigne@ens-paris-saclay.fr">thomas.lavigne@ens-paris-saclay.fr</a></li>
      </ul>

    center:
      - icon: github
        href: https://github.com/Th0masLavigne
      - icon: twitter
        href: https://x.com/Thomas_Lavigne_
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-l-7a6608109/
      - text: "{{< iconify fa-brands:orcid >}}"
        href: https://orcid.org/0000-0003-2690-3542
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=FYXQf_UAAAAJ
      - text: "{{< iconify simple-icons:researchgate >}}"
        href: https://www.researchgate.net/profile/Thomas-Lavigne-2

    left: |
      <small>
        &copy; 2025 Thomas Lavigne ‚Äî All rights reserved.<br>
        <a href="https://quarto.org/">Built with Quarto</a>
      </small>

  # reader-mode: if side bar allows to hide
  # reader-mode: true
  # repo-url: https://github.com/Th0masLavigne/Resume.git
  # repo-actions: [edit, source, issue]


# https://quarto.org/docs/output-formats/html-themes.html
format:
  html:
    email-obfuscation: javascript
    theme:
      light: [flatly,style_site.scss]
      dark: [darkly,style_site_dark.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    smooth-scroll: true
    include-after-body:
      text: |
        <script type="application/javascript" src="custom_hal.js"></script>
        <script type="application/javascript" src="carousel.js"></script>

header-includes:
  - <script src="carousel.js"></script>